/*	SCCS Id: @(#)date.h	3.4	2002/02/03 */

/* This source file is generated by 'makedefs'.  Do not edit. */
#define BUILD_DATE "Sat Sep 28 14:01:46 2013"
#define BUILD_TIME (1380369706L)

#define VERSION_NUMBER 0x03040300UL
#define VERSION_FEATURES 0x181a0cc6UL
#define IGNORED_FEATURES 0x00800000UL
#define VERSION_SANITY1 0x211b117eUL
#define VERSION_SANITY2 0xb8d24950UL

#define VERSION_STRING "3.4.3"
#define VERSION_ID \
 "Unix NetHack Version 3.4.3 - last build Sat Sep 28 14:01:46 2013."

